apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nzbhydra2
spec:
  selector:
    matchLabels:
      app: nzbhydra2
  serviceName: nzbhydra2
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: nzbhydra2
    spec:
      containers:
        - name: nzbhydra2
          image: lscr.io/linuxserver/nzbhydra2:8.8.0@sha256:7e2a67818efe2d80f11b1dad16a493508ac9ab6e2bce72a7c87db2e8b1789b98
          imagePullPolicy: Always
          ports:
            - containerPort: 5076
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          env:
            - name: PUID
              value: "10001"
            - name: PGID
              value: "10001"
            - name: TZ
              value: "America/Los_Angeles"
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: downloads
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
