apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/deployment
  - key.yaml
  - secrets.yaml

components:
  - ../../kustomize/components/ingress
#  - ../../kustomize/components/security-context

namePrefix: renovate-pr-triage-
labels:
  - pairs:
      app.kubernetes.io/name: renovate-pr-triage
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/ansg191-lab/renovate-pr-triage
    newTag: main@sha256:9ba9c5d275960dfc27114e4e99ded5b03f957ff2628e6ff8c73ddcd853fa14ce

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=renovate-pr-triage.internal

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    path: patch-deployment.yaml
  - target:
      kind: Deployment
    path: patch-deployment2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
