apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: audiomuse-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: audiomuse
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu", "memory"]
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: audiomuse-worker-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: audiomuse-worker
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu", "memory"]
