apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbt-exporter
  labels:
    app: qbt-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbt-exporter
  template:
    metadata:
      name: qbt-exporter
      labels:
        app: qbt-exporter
    spec:
      containers:
        - name: qbt-exporter
          image: ghcr.io/martabal/qbittorrent-exporter:v2.0.1@sha256:ddf2bff9b357e50be4ddb699b6489ac5a49e4fac8c7dc5d4ca2abe1e5855f4dd
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: exporter-config
            - secretRef:
                name: exporter-auth
          ports:
            - containerPort: 8090
              protocol: TCP
              name: http
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: Always
