apiVersion: v1
kind: Namespace
metadata:
  name: ha-proxy
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ha-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ha-proxy
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: rpi5/ha-proxy
  syncPolicy:
    automated: {}
