apiVersion: v1
kind: Namespace
metadata:
  name: nametag
  labels:
    anshulg.com/access-mail: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nametag
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nametag
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: rpi5/nametag
  syncPolicy:
    automated:
      prune: true
