apiVersion: v1
kind: Namespace
metadata:
  name: renovate-pr-triage
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate-pr-triage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: renovate-pr-triage
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: rpi5/renovate-pr-triage
  syncPolicy:
    automated:
      prune: true
