apiVersion: v1
kind: Namespace
metadata:
  name: romance-io-api
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: romance-io-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: romance-io-api
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: rpi5/romance-io-api
  syncPolicy:
    automated:
      prune: true
