apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unbound
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: blocky
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: rpi5/blocky/unbound
    # No directory: block - ArgoCD auto-detects kustomization.yaml.
  syncPolicy:
    automated: {}
