apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset
  - serverstransport.yaml
  - middleware.yaml
  - policy.yaml

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress

configurations:
  - nameReferences.yaml

namePrefix: anthropic-
labels:
  - pairs:
      app.kubernetes.io/name: anthropic
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/ansg191/claude-auth-proxy
    newTag: main@sha256:657cf8e36b190e4307f051b35c6e5bc45b6a3b6d882494fbfe40a7158aefa602

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=anthropic.internal
      - DIRECT_DOMAIN=anthropic.anshulg.direct
  - name: env-config
    literals:
      - RUST_LOG=debug,h2=info

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
  - target:
      kind: IngressRoute
    path: patch-ingress.yaml
