---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: secret
  namespace: browserless
spec:
  encryptedData:
    TOKEN: AgB4U0RLrNL0gvtKhViKTMd52P9tuXaCZDp6O8+WN7T7X0UnMxb8lQ1VPvfpeK1pbxIAjmtHbAJb5+VmGs7yn54zA5dHunmaN7d0nJrPX/IEGjcc1gR2eaZKsJKJT9oPGOSdXSJHtfhBYywKqwkq2eEt94/XEYBOocRDCiXkwz+IuTNMDsGcOVaOZFM5/B+NeO6nJqZo7jFrJwLwIS4YQikDleScv58E3ACgirCh3U1DAXd8KLvwFhiqGm+Ntj5yNziOMHi503oy+AoNJGKpUjgxhFLo0/954wcWlwjSLWL0XvfFSjsZbzD273KmEmfHlyU1tUUcTfvLTXZjTh9K2SUnJ2/Z66Kjz0oLpwGlbLjZxOGXW65fbdwCAJD8W/jtX2vW91BjD0cGNE84xSS3SRCSQg89XedXrPv4sDVxfrSXN0AeKpe7C/AVvIu+Y8mX9LJyZF8pI/RezP3Cn8POOFMQyeGDTLyvC+sHBFqnw2wSKUNUuqZLXxtlObRikfQ6OkJf5e+6vw9qBYKwum1vKd25RmU465Ka0VdqujgXbebwbaiUw+TdHa73b94nOIeyTdAkWx/rTTJGXJAQdA8hE/nJpPbfmlJDsTXyHMuczzXPUU/K3ZkGRKseNRSEkpL2lqEwltWAQC03wqtAco3S6/TFcH/lAXMJwMaLw35m5KN1+b1FL+/6geA0SGaLHmp604UCMpeoInZarR0NdWwXDixYkztdCSzn5B3GGIU7WUfJRjiZWC8HNkMX8jTPoa0kK2JfmRpgdA7/4p/bHBlunOYa
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: secret
      namespace: browserless
    type: Opaque
