apiVersion: apps/v1
kind: Deployment
metadata:
  name: empty
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: main
  template:
    metadata:
      labels:
        app.kubernetes.io/component: main
    spec:
      containers:
        - name: app
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: flowise-secrets
          volumeMounts:
            - mountPath: /data/Flowise
              name: data
          readinessProbe:
            httpGet:
              port: 3000
              path: /
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              port: 3000
              path: /
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 2Gi
      volumes:
        - name: data
          hostPath:
            path: /data/Flowise
            type: DirectoryOrCreate
