apiVersion: batch/v1
kind: CronJob
metadata:
  name: mam-point-spender
spec:
  schedule: "18 13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mam-point-spender
              image: ghcr.io/ansg191/mam-point-spender:0.1.6@sha256:c4616abd28357ca6d6ef50e143d2f272465c48c108802d86d9e7ba0818118351
              imagePullPolicy: IfNotPresent
              workingDir: /tmp
              envFrom:
                - configMapRef:
                    name: env
                - secretRef:
                    name: secret
              volumeMounts:
                - mountPath: /tmp
                  name: workdir
              securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                runAsGroup: 10001
                privileged: false
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          restartPolicy: OnFailure
          volumes:
            - name: workdir
              persistentVolumeClaim:
                claimName: mam-point-spender-workdir
