apiVersion: batch/v1
kind: CronJob
metadata:
  name: mam-point-spender
spec:
  schedule: "18 13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mam-point-spender
              image: ghcr.io/ansg191/mam-point-spender:0.1.5@sha256:119ee1871e0a682b7449014f2522c4cb187943da8162f98b4d70b54e53b94923
              imagePullPolicy: IfNotPresent
              workingDir: /tmp
              envFrom:
                - configMapRef:
                    name: env
                - secretRef:
                    name: secret
              volumeMounts:
                - mountPath: /tmp
                  name: workdir
              securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                runAsGroup: 10001
                privileged: false
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          restartPolicy: OnFailure
          volumes:
            - name: workdir
              persistentVolumeClaim:
                claimName: mam-point-spender-workdir
