apiVersion: batch/v1
kind: CronJob
metadata:
  name: mam-point-spender
spec:
  schedule: "18 13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mam-point-spender
              image: ghcr.io/ansg191/mam-point-spender:0.2.0@sha256:1b6f0ff96a3aa0347f67ca205dc11a03a58eaa8c2dc44527fdab097884d51aee
              imagePullPolicy: IfNotPresent
              workingDir: /tmp
              envFrom:
                - configMapRef:
                    name: env
                - secretRef:
                    name: secret
              volumeMounts:
                - mountPath: /tmp
                  name: workdir
              securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                runAsGroup: 10001
                privileged: false
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          restartPolicy: OnFailure
          volumes:
            - name: workdir
              persistentVolumeClaim:
                claimName: mam-point-spender-workdir
