---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  namespace: mam-point-spender
spec:
  encryptedData:
    MAMID: AgCt/NrNfv8zzuVfXmn0SlJg1PQiDvyGmfvZpDIxjobxrMBdiork2+Kb43/gfydWWSM9qzHamHBxyABUtNgQX4Aewd+Yy4lFzILpRmvIW6CPdoUI8qKZza4eNHBurL9097+Y8dwdIYr0in6vQLyJNdBXKhbgHTDupbCKOykYAnUew+3dav90Bq8lSKOrcEk7ov4WCI9D/sD1GLbHego+aGF/ReJWZF+O2awARy3ZpLQ5iblTZctZIk+ps4vDv5sc4DpQ2mpN8sKVe+K8ullzZ+BB/csAKC24CTH5/QCkSd2M/dqzBzo0gt4sboErzKbTLNYi0KUUz+/Rxebb7FyEMJbykWzbYIp1QL/prBppdGg9F3x5TUJyKEpM/t1LHw4y9S7ycTLIiCFvt14Mc18grerHUJDpACB3noxGSlb4v4EzJvIqkmhKBp0L6Skrg0a2fZ0K9ZLH5zaWkkBJ3ivyoBaR0E8BUxQ+32erg1e4rOlgKA9hCam3pXMsLxXWlG2Ve13ZR5HrWsgAqVk4oklM6taH0sL0WlLAK3F6czEVjK/mBfkio0szwIZXUYXw8o7014uKn4hsADnK530+L4iiaEW4S1HzO8sR2QjR72anqosKLX8LAFfsw4IHxFiFvY6UXXEyqenpFXOA/+VIc7jWCoIA2stsj2LROtVisVC/OfqMOerKHm85+t57UlC4vRF28oGAPmPOXUos3NgjjvjX3Tfln0Svi6SOitvd1qI7JhE8JHiKiJf8Bg1odkTEWi1n2GFcgCqZ6B3A80ko/f7G5IWXBmRiy6ICoi2Sc4erKPvBb1jxTveVzyTzY6iZmfn2ilCvRLt5+blY8w510CWb26FhSOPRV/iqsh05Zh/udxnNLwDqBgUqhuUrkZnMi6XV8XGJpPnxide/e8bnAfAW/yQKGLi5Odv/MV4CEuyUKTr52pjYIns+BlU7mGwUeknyDukx9IVG63LaN5K60wUMeORkpvewQ8EgVQ8JNSIZOuY7oJtcCCxWGE63KiARZyGD8vHRiTi/zw1g/+U/QM0LEIgvGFHJQhNAILycCj74vhHO9haYOqhqgwQ4QqCZMj6KygC/B9z7
  template:
    metadata:
      name: secret
      namespace: mam-point-spender
    type: Opaque
