apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: audioserve-
labels:
  - pairs:
      app.kubernetes.io/name: audioserve
    includeSelectors: true

images:
  - name: busybox
    newName: izderadicka/audioserve
    newTag: latest@sha256:aac13420d5ef2cf322fdffecd49108708b82096d6a04b1db88ec7e7e9fc39fb3

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=audioserve.internal
      - DIRECT_DOMAIN=audioserve.anshulg.direct
      - TS_HOST=audioserve
  - name: config
    files:
      - config.yaml
  - name: env-config
    literals:
      - AUDIOSERVE_CONFIG=/config/config.yaml
      - AUDIOSERVE_DATA_DIR=/data
      - AUDIOSERVE_NO_AUTHENTICATION=true

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
