apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cross-seed-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: cross-seed
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu", "memory"]
