apiVersion: v1
kind: ConfigMap
metadata:
  name: ragflow-config
  namespace: ragflow
data:
  DOC_ENGINE: "infinity"
  MYSQL_HOST: "ragflow-mysql"
  MYSQL_PORT: "3306"
  MYSQL_DBNAME: "rag_flow"
  MINIO_HOST: "ragflow-minio"
  MINIO_PORT: "9000"
  MINIO_CONSOLE_PORT: "9001"
  REDIS_HOST: "ragflow-redis"
  REDIS_PORT: "6379"
  INFINITY_HOST: "ragflow-infinity"
  INFINITY_THRIFT_PORT: "23817"
  INFINITY_HTTP_PORT: "23820"
  SVR_HTTP_PORT: "9380"
  TZ: "America/Los_Angeles"
  DEVICE: "cpu"
  REGISTER_ENABLED: "1"
  DOC_BULK_SIZE: "4"
  EMBEDDING_BATCH_SIZE: "16"
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "1"
  THREAD_POOL_MAX_WORKERS: "128"
  DISABLE_PASSWORD_LOGIN: "false"
  STACK_VERSION: "8.11.3"
  ES_HOST: "es01"
  ELASTIC_PASSWORD: "unused"
