apiVersion: v1
kind: ConfigMap
metadata:
  name: ragflow-infinity-config
  namespace: ragflow
data:
  infinity_conf.toml: |
    [general]
    version = "0.7.0"
    time_zone = "utc-8"

    [network]
    server_address = "0.0.0.0"
    postgres_port = 5432
    http_port = 23820
    client_port = 23817
    connection_pool_size = 128

    [log]
    log_filename = "infinity.log"
    log_dir = "/var/infinity/log"
    log_file_max_size = "10GB"
    log_file_rotate_count = 10
    log_level = "info"
    log_to_stdout = true

    [storage]
    data_dir = "/var/infinity/data"
    persistence_dir = "/var/infinity/persistence"
    catalog_dir = "/var/infinity/catalog"
    snapshot_dir = "/var/infinity/snapshots"
    optimize_interval = "10s"
    cleanup_interval = "60s"
    compact_interval = "120s"

    [buffer]
    buffer_manager_size = "2GB"
    lru_num = 7
    memindex_memory_quota = "512MB"
    temp_dir = "/var/infinity/tmp"
    result_cache = "off"

    [wal]
    wal_dir = "/var/infinity/wal"
    checkpoint_interval = "86400s"
    wal_compact_threshold = "1GB"
    wal_flush = "only_write"

    [resource]
    resource_dir = "/usr/share/infinity/resource"
