apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset
  - cronjobs.yaml
  - secrets.yaml

components:
#  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress
  - ../../kustomize/components/security-context

namePrefix: nametag-
labels:
  - pairs:
      app.kubernetes.io/name: nametag
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/mattogodoy/nametag
    newTag: 0.44.3@sha256:bd577144941fb4ba89570d86e29468f95b53a304e18688208c36e05e3161d009

configMapGenerator:
  - name: domain-config
    literals:
      - DIRECT_DOMAIN=nametag.anshulg.direct
  - name: env-config
    literals:
      - DB_HOST="rpi4.anshulg.direct"
      - DB_PORT="5432"
      - DB_NAME="nametag"
      - DB_USER="nametag"
      - NEXTAUTH_URL="https://nametag.anshulg.direct"
      - SMTP_HOST="mail.mail.svc.cluster.local"
      - SMTP_PORT="587"
      - SMTP_SECURE="false"
      - SMTP_REQUIRE_TLS="false"
      - EMAIL_DOMAIN="anshulg.com"
      - DISABLE_REGISTRATION="true"

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
