apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyber-chef
  labels:
    app: cyber-chef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyber-chef
  template:
    metadata:
      name: cyber-chef
      labels:
        app: cyber-chef
    spec:
      containers:
        - name: cyber-chef
          image: mpepping/cyberchef:v11.2.0@sha256:40de0167deab2637706ded13626c30739bc7ae526bfecaf42841e0e1293d7179
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
      restartPolicy: Always
