apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyber-chef
  labels:
    app: cyber-chef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyber-chef
  template:
    metadata:
      name: cyber-chef
      labels:
        app: cyber-chef
    spec:
      containers:
        - name: cyber-chef
          image: mpepping/cyberchef:v11.5.0@sha256:d75426ccf924157f4ade18d319b6eb0963559ac228d5e4a59b4c8fefcad9b420
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
      restartPolicy: Always
