apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-bypass
  labels:
    app.kubernetes.io/component: cloudflare-bypass
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: cloudflare-bypass
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app.kubernetes.io/component: cloudflare-bypass
    spec:
      containers:
        - name: proxy
          image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest@sha256:0e679c1c0f6ac3209d233c2b7e99737f39a137987171b5bf30b15ef53a01ce33
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          env:
            - name: WORKERS
              value: "3"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
      nodeSelector:
        kubernetes.io/arch: amd64
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflare-bypass
spec:
  selector:
    app.kubernetes.io/component: cloudflare-bypass
  ports:
    - protocol: TCP
      port: 8000
      targetPort: http
      name: http
  type: ClusterIP
