apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/deployment
  - cloudflare-bypass.yaml
  - valkey.yaml

components:
  - ../../kustomize/components/ingress

namePrefix: romance-io-api-
labels:
  - pairs:
      app.kubernetes.io/name: romance-io-api
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/ansg191/romance-io-api
    newTag: 0.1.3@sha256:5ca91a8eb10ff5905593947bd8cb536f2c0bc8ab77fffccceb20a30d54918be5

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=romance-io-api.internal

patches:
  - target:
      kind: Deployment
      name: deployment
    path: patch-deployment-ports.yaml
  - target:
      kind: Deployment
      name: deployment
    path: patch-deployment.yaml
  - target:
      kind: Service
      name: svc
    path: patch-service.yaml
