apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/deployment
  - cloudflare-bypass.yaml
  - valkey.yaml

components:
  - ../../kustomize/components/ingress

namePrefix: romance-io-api-
labels:
  - pairs:
      app.kubernetes.io/name: romance-io-api
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/ansg191/romance-io-api
    newTag: 0.1.2@sha256:efd42e521626fd8e490784439df663bf4b9d40266012315a62ba9dc13ce9050c

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=romance-io-api.internal

patches:
  - target:
      kind: Deployment
      name: deployment
    path: patch-deployment-ports.yaml
  - target:
      kind: Deployment
      name: deployment
    path: patch-deployment.yaml
  - target:
      kind: Service
      name: svc
    path: patch-service.yaml
