apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: patchmon-backend
  labels:
    app: patchmon-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patchmon-backend
  serviceName: patchmon-backend
  template:
    metadata:
      name: patchmon-backend
      labels:
        app: patchmon-backend
    spec:
      containers:
        - name: patchmon-backend
          image: ghcr.io/patchmon/patchmon-backend:1.4.0@sha256:6fc3ff6a02a2685ee83bcf8b0658200e211fce432219ae05317d94bc079d9c90
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              protocol: TCP
          envFrom:
            - configMapRef:
                name: patchmon-backend-env
            - secretRef:
                name: patchmon-backend-secrets
          volumeMounts:
            - mountPath: /app/agents
              name: agent-files
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: agent-files
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
