apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/deployment

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: whoami-
labels:
  - pairs:
      app.kubernetes.io/name: whoami
    includeSelectors: true

images:
  - name: busybox
    newName: traefik/whoami
    newTag: v1.12.0@sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=whoami.internal
      - TS_HOST=whoami

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    path: patch-deployment.yaml
