apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/deployment

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: glance-
labels:
  - pairs:
      app.kubernetes.io/name: glance
    includeSelectors: true

images:
  - name: busybox
    newName: glanceapp/glance
    newTag: v0.8.5@sha256:32ab73d80f2b8b5fb0735b0431deb36b93fbb6b2fb43592449b0178c8b83e350

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=glance.internal
      - TS_HOST=glance
  - name: glance-config
    files:
      - glance.yml=config/glance.yml
      - home.yml=config/home.yml

patches:
  - target:
      kind: Deployment
    path: patch-deployment.yaml
  - target:
      kind: Deployment
    path: patch-deployment2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
