apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbit-manage
  labels:
    app: qbit-manage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbit-manage
  serviceName: qbit-manage
  template:
    metadata:
      name: qbit-manage
      labels:
        app: qbit-manage
    spec:
      containers:
        - name: qbit-manage
          image: ghcr.io/stuffanthings/qbit_manage:v4.6.6@sha256:e4bb989719c9f3c7218c36f688de03cea2b95f0664fa89ba8095ad7ed0eeefed
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: qbt-manage-env
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
          securityContext:
            runAsUser: 2020
            runAsGroup: 3002
      restartPolicy: Always
      securityContext:
        fsGroup: 3002
      volumes:
        - name: data
          hostPath:
            path: /data
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
