apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbit-manage
  labels:
    app: qbit-manage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbit-manage
  serviceName: qbit-manage
  template:
    metadata:
      name: qbit-manage
      labels:
        app: qbit-manage
    spec:
      containers:
        - name: qbit-manage
          image: ghcr.io/stuffanthings/qbit_manage:v4.7.0@sha256:8786f2efc6fb8e26281f09bf6c5d0004e2d2420fd4781af0aed123ae01558e21
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: qbt-manage-env
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
          securityContext:
            runAsUser: 2020
            runAsGroup: 3002
      restartPolicy: Always
      securityContext:
        fsGroup: 3002
      volumes:
        - name: data
          hostPath:
            path: /data
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
