apiVersion: v1
kind: Namespace
metadata:
  name: trivy-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: internal
  source:
    chart: trivy-operator
    repoURL: ghcr.io/aquasecurity/helm-charts
    targetRevision: 0.32.1
    helm:
      values: |
        trivy:
          ignoreUnfixed: true
          severity: HIGH,CRITICAL
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: trivy-system
  syncPolicy:
    automated: {}
