apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/deployment
  - secrets.yaml

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: jellystat-
labels:
  - pairs:
      app.kubernetes.io/name: jellystat
    includeSelectors: true

images:
  - name: busybox
    newName: cyfershepard/jellystat
    newTag: 1.1.12@sha256:e61c759ec706da378bc8374e797da1dfd298ab30f804cefd82d192c301a888c7

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=jellystat.internal
      - TS_HOST=jellystat
  - name: jellystat-config
    literals:
      - POSTGRES_IP=192.168.1.9
      - POSTGRES_PORT=5432
      - POSTGRES_USER=jellystat
      - POSTGRES_DB=jfstat
      - TZ=America/Los_Angeles

patches:
  - target:
      kind: Deployment
    path: patch-deployment.yaml
  - target:
      kind: Service
    path: patch-service.yaml
