---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: vm
spec:
  encryptedData:
    admin-password: AgCfsykmmmPTNtfdh5f6oLyWTlknCccCCEvIT8wNtHpuAkcXmKibY/GsOtWfTVqtp0h/zCvofGt+tJzhtYy9ExcYMmoOt7UqSOU2A5kGeqS9o5TzFm/8qxagZrcvOpfCIe9N+/7FR0FF14tpRm1NiG0OAXUdK8Sy+Qu4DHO3Jbc03FWVSYZxwi7uElaHlCmLEtkvYeL2Rs5trdMgqT/L2GjVPOFzQFAHDBdgEUoTOOwz8n2DLv3Cqc0hz9zyEE/AfiI3hN7lvIGhejN7ZIiYnmzZaznSKtT80xcKwXnml/1f3Op2xc6SGn+ypNiBoPBIbu5OaVvvLgujmlxEcpcjHfXLb8+z/mRJcgM+iHaOm3jy85+yb6UuWRD6bXk3SIriteO6evZmZso7tKarEUbsmV8q5EsQjVQ2LORfJmr1r8QSDx6PtAPyAAw/U22B02Ql4VPVsCzKYD42sXBiQ1oy6YL3W4dTKG/R895X+XlYzz44ovP2BZYuilrXxQwtrNKXhnRt/1tqLlgJqxB8F5ThB3QUQ81S9YA+h6GcEaNPZ4iSGaHObwb4WbFAKi9uz/nm+8yKds1tJlhKQiuAyz1z60YsfrPvtdGIWah/NEm6cA6A+EJFd+bqLpjXr8dI/BJjnZfNaTFUwokLK/56+XjxN3SrA4BsTLiCDAMmWU9RieQEa59zIW4zPb800hfrx5HXnr8dpMISXaOqOLTIpTe/Z8r8Je3/gg8sRc5TeS6W7xx6uDNouUQGAouTctTcmauthTiIwrHjpjX2Uw7cdMOS15YC
    admin-user: AgAkGl+dJpZqtxMdkEA5aOvqzOFenYGn1/LsI4p4CgOKq3OjHoLwkOy+kqS0FHFQKZrc4eJwbpmN2m/DLqFQIEzt50yaghYKUIXqK+V7K5F/N0tFMdA7e7U7iXlRgDhC9nyRor/toPAuGsgGpUQexWroYKFiQmJRKId9q2gK2tQIaYh+io29Zu1khXrxqXUwJojqosV4AYE322FfgLg+QzIs5Bg8D3NjzF2QL82kOvub0S+k8AV9TlDKo//0rylxwL6/NuPcJ+Z4/6VptsmFq7DhrXwXBVST4BvMQOdEjcVKR/aTvmuZ3vPLggkc+oJ/s2ITxCm6vr+AvUmxHNNJyDMW8ZGVFl3ILpFIxXhNYGV7VzXikOPN+i5pW3BEQJHDiS6dfTtXwyVmx/QTVi13FAyb5y18i0faGkKoXs4DXM1IC95XtnGxBjWLoH/KWNWP121bS9ykqdsnoV90s8UJNPQFiwz7/xzoV9mO0jrO7IcnTMHuEIdyegcdNSP5dPYHiJfMiWFVs9wKcP1gCaA3zORsTt6OwuUct8LuyHnafc7tL57x+4WRuyuLClU0JE25jUoje9c7FX783WFIm5rk42f4e5wevLOujQ/Rmj/YzoJpcE6EWJjH2AygJJfrIJXA8RtiHXNwfwQVtyiLxiyKoTJ7+7Y9Z8A4hmhXZ/vRzIkhtyOh9OgXZvetW9yN28yyJPFKhGr1tQ==
  template:
    metadata:
      name: grafana-admin
      namespace: vm
    type: Opaque
