apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/VictoriaMetrics/operator/config/base-with-webhook?ref=v0.69.0
  - vmsingle.yaml
  - vmagent.yaml

images:
  - name: manager
    newName: victoriametrics/operator
    newTag: v0.69.0
