apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/VictoriaMetrics/operator/config/base-with-webhook?ref=v0.74.1
  - vmsingle.yaml
  - vlsingle.yaml
  - vmagent.yaml
  - vlagent.yaml
  - vmalert.yaml
  - vmalertmanager.yaml
  - vmalertmanagerconfig.yaml
  - discord-webhook.yaml
  - vmrules/infrastructure.yaml
  - vmrules/workloads.yaml
  - vmrules/stack.yaml
  - grafana.yaml
  - grafana-admin.yaml
  - node-exporter.yaml
  - node-scrape.yaml

images:
  - name: manager
    newName: victoriametrics/operator
    newTag: v0.74.1@sha256:7310c4a80b94f530c5f0b1fcf6d6eaf933f39cc5704e983900d9cfd6b31f9dc1
