apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/VictoriaMetrics/operator/config/base-with-webhook?ref=v0.73.1
  - vmsingle.yaml
  - vlsingle.yaml
  - vmagent.yaml
  - vlagent.yaml
  - vmalert.yaml
  - vmalertmanager.yaml
  - vmalertmanagerconfig.yaml
  - discord-webhook.yaml
  - vmrules/infrastructure.yaml
  - vmrules/workloads.yaml
  - vmrules/stack.yaml
  - grafana.yaml
  - grafana-admin.yaml
  - node-exporter.yaml
  - node-scrape.yaml

images:
  - name: manager
    newName: victoriametrics/operator
    newTag: v0.73.1@sha256:de263adc8ab575aa636ce9974ebf282a951559297e54e26cda77e07d003403d7
