apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubelet
spec:
  scheme: https
  tlsConfig:
    insecureSkipVerify: true
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  honorLabels: true
#  relabelConfigs:
#    - action: labelmap
#      regex: __meta_kubernetes_node_label_(.+)
  jobLabel: kubelet
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubelet-cadvisor
spec:
  scheme: https
  tlsConfig:
    insecureSkipVerify: true
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  path: /metrics/cadvisor
  honorLabels: true
  honorTimestamps: false
#  relabelConfigs:
#    - action: labelmap
#      regex: __meta_kubernetes_node_label_(.+)
  jobLabel: kubelet
