apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: main
spec:
  replicaCount: 1
  selectAllByDefault: true
  disableNamespaceMatcher: true
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
