apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: main
spec:
  retentionPeriod: "1y"
  removePvcAfterDelete: false
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 80Gi
    storageClassName: local-path
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 2Gi
