apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset
  - secrets.yaml

components:
  - ../../kustomize/components/direct-ingress
  - ../../kustomize/components/security-context

namePrefix: hister-
labels:
  - pairs:
      app.kubernetes.io/name: hister
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/asciimoo/hister
    newTag: v0.13.0-debug@sha256:f1db532f5b1861e0bd42de2778f02f13fc9483dcb6ed48ca228ff439f17aabf8

configMapGenerator:
  - name: domain-config
    literals:
      - DIRECT_DOMAIN=hister.anshulg.direct
  - name: config
    files:
      - config.yml

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
