apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset
  - secrets.yaml

components:
  - ../../kustomize/components/direct-ingress
  - ../../kustomize/components/security-context

namePrefix: hister-
labels:
  - pairs:
      app.kubernetes.io/name: hister
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/asciimoo/hister
    newTag: v0.20.0-debug@sha256:75fd8cab8e8f0101049c9ce3e463a4bd891dbf9b30f566879b203b47ec6eaa1f

configMapGenerator:
  - name: domain-config
    literals:
      - DIRECT_DOMAIN=hister.anshulg.direct
  - name: config
    files:
      - config.yml

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
