---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: secrets
  namespace: hister
spec:
  encryptedData:
    HISTER__SERVER__DATABASE: AgCxZztPPBjjEqWK0ZfQYHiIRuF86WNyUKTKauy5id1tOvKD7O9OhVbqQrc+5nikXLwV8bECR5k199eIVUT8CnfZae/CryRd9RHWUltBVe3gQ4bEz3NA4XNB0NlOJQ4mH5tUsz4GyGlo1Sez1bP53W82Xns8bmpEIOtN9tfegIrddaLZ4W1sAFaIhjegBqscWNSmt79Sciog5GipFQoUSnV7O9SotPHnYc+9dNWZ7vkb764DqOlTSOlGzPOcZJYF2tiVPRQ0xLiWLnNWqm+y3EHQVDG1hdOBzFO10PALStOKp+zck3UkQydHYDFs0kQeBVbR3hV6vFmnXY2YzOUoPnTtdSdjtSHUCQopW+EKPv41LwbNm8xr13k/ItPyvmeXgI47YXNatwvQRiJ1l7yj/5TtMgw/OV0BLBK7mCOzBv56D1l4XUzIG5wiGWnsFnwDdXukTwNlKx03eKgVDnUX/5WeYOpuQADd/AsveVsibAsF0/mkMbhlfm99K2MssTTWrb6jZXnXAj3+QYRGFP4O9HeI8igL9incxO9hKaHNkgl7oQKs46vzmO+X8tXNe+KpzntBtVNyt2rEEIjw0gUL6dssAhbVWQrVTmo2gVwYup5Y+YSKn6EisDatQGAhLXeML1+oYCRhNKm+wR6gYlrZT+gvrFrsm7ZWdvduRRSNzCFjp6oK+sUluWKXApOd4EOkt4jEntiR6S6TNTySbZAEu80xP0fKcUwI/nzq7PrwF7ZOfAly0oAPgDTb0ohYWRrV/lPP78wqmWEKZdg5Y5ygbajF+WbtAkQHjrLOd0ddlc5XsFLeAa7WL92JdFhL12gN8qxSRoMlrDscHbFhhz0SOc4kM7BaWNzGlOecEf3PpUD5OC/NQn45bhxX/PkpotBhG6+bSwzyDjYl+fJBqLUCAeodpvP8BC949WJTtxOvu6u6e+EG1kx3tUeBJ9+fM8pqMd8vQJQZNRySzTJOe3MZE7wlRufaDISg
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: secrets
      namespace: hister
    type: Opaque
