server:
  # Do not print log lines to inform about local zone actions
  log-local-actions: no
  # Do not print one line per query to the log
  log-queries: no
  # Do not print one line per reply to the log
  log-replies: no
  # Print log lines that say why queries return SERVFAIL to clients
  log-servfail: yes

  # Set logging level
  #   Level 0: No verbosity, only errors.
  #   Level 1: Gives operational information.
  #   Level 2: Gives detailed operational information including short info per query.
  #   Level 3: Gives query level information, output per query.
  #   Level 4: Gives algorithm level information.
  #   Level 5: Logs client identification for cache misses.
  verbosity: 2

  use-syslog: no
  log-time-ascii: yes
  # logfile: "" (image default) -> stderr -> captured by `kubectl logs`.
