apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb
  template:
    metadata:
      name: mariadb
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: lscr.io/linuxserver/mariadb:11.4.12@sha256:b68d35ff2da41e568f51e0370a7e1c3ce693fecdacbed061b4b0be5b924f14bb
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "10001"
            - name: PGID
              value: "10001"
            - name: TZ
              value: "America/Los_Angeles"
          envFrom:
            - secretRef:
                name: db-env
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: data
          readinessProbe:
            exec:
              command:
                - "mariadb-admin"
                - "ping"
                - "-h"
                - "localhost"
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
      restartPolicy: Always
      securityContext:
        fsGroup: 10001
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
