apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: booklore
  labels:
    app: booklore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booklore
  serviceName: booklore
  template:
    metadata:
      name: grimmory
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: booklore
    spec:
      containers:
        - name: grimmory
          image: ghcr.io/grimmory-tools/grimmory:v3.0.2@sha256:4557a78321add7d70bef7c0b89c2617c8c023246ae39698bc2cbe636f8c97f9b
          imagePullPolicy: IfNotPresent
          env:
            - name: USER_ID
              value: "2019"
            - name: GROUP_ID
              value: "3002"
            - name: TZ
              value: "America/Los_Angeles"
            - name: BOOKLORE_PORT
              value: "6060"
            - name: "API_DOCS_ENABLED"
              value: "true"
          envFrom:
            - secretRef:
                name: booklore-web-env
          ports:
            - containerPort: 6060
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /app/data
              name: data
            - mountPath: /books
              name: books
            - mountPath: /bookdrop
              name: ingest
          readinessProbe:
            httpGet:
              port: 6060
              path: /
          livenessProbe:
            tcpSocket:
              port: 6060
            initialDelaySeconds: 60
      restartPolicy: Always
      securityContext:
        fsGroup: 3002
      volumes:
        - name: books
          hostPath:
            path: "/data/Books"
        - name: ingest
          hostPath:
            path: "/data/BookImport/booklore"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
