apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/deployment
  - middleware.yaml

components:
#  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: homeassistant-
labels:
  - pairs:
      app.kubernetes.io/name: homeassistant
    includeSelectors: true

images:
  - name: busybox
    newName: dhi.io/nginx
    newTag: 1.31-debian13-dev@sha256:39366ec9be9def4a8667efc976a2dfcc15024166efbe97bc50a1d6333db0472a

configMapGenerator:
  - name: domain-config
    literals:
#      - DOMAIN=homeassistant.internal
      - DIRECT_DOMAIN=homeassistant.anshulg.direct
      - TS_HOST=homeassistant
  - name: nginx-proxy-template
    files:
      - default.conf.template=default.conf.template
  - name: nginx-env
    literals:
      - UPSTREAM_HOST=192.168.1.10:30103

patches:
  - target:
      kind: Deployment
    path: patch-deployment.yaml
  - target:
      kind: Deployment
    path: patch-deployment2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
  - target:
      kind: IngressRoute
    path: patch-ingress-buffering.yaml
