apiVersion: apps/v1
kind: Deployment
metadata:
  name: yamtrack
  labels:
    app: yamtrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yamtrack
  template:
    metadata:
      name: yamtrack
      labels:
        app: yamtrack
    spec:
      containers:
        - name: yamtrack
          image: ghcr.io/fuzzygrim/yamtrack:0.25.3@sha256:00acf008bca8171226063bc0f8f08ef7ffe24a10bcebf8676cce335ce312c307
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: secret-env
          readinessProbe:
            httpGet:
              port: http
              path: /health/
            timeoutSeconds: 5
      restartPolicy: Always
