apiVersion: apps/v1
kind: Deployment
metadata:
  name: yamtrack
  labels:
    app: yamtrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yamtrack
  template:
    metadata:
      name: yamtrack
      labels:
        app: yamtrack
    spec:
      containers:
        - name: yamtrack
          image: ghcr.io/fuzzygrim/yamtrack:0.25.2@sha256:928df13c46c9f615b37f5ef1eb5a87fc8813f5941f28c7d8227af73d291b0d19
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: secret-env
          readinessProbe:
            httpGet:
              port: http
              path: /health/
            timeoutSeconds: 5
      restartPolicy: Always
