---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gemini-api-credentials
  namespace: audiomuse
spec:
  encryptedData:
    GEMINI_API_KEY: AgAYuVfAVl0KnMPgd3cjl7cRCGghfDKBUyyXFoMlNJ/E1Lw0mKbY2RVp3FFAQ9IIfIQozOXtSkiu0QOl2TraDvJXAalvpBH27b9mv2Wz+cQaWug7wbcvRORZQMGL0mtGl4b6lgrGxtV4gfI4LqTAOgLQYdl99vtjXy9j9O43uB2d0QBPnN7ZvZ7R5zkALae7kgvSOQ9xb1gM0L/jGlmH3iig06xSi9zCcxPE7FlWS1KyFlqht10VM+2cgx3Pn7S5WLakbrvAXbX4Ui19AOVmnrNKROhoOF0T4XOPHtMaASrVWEwTcQPy0bG8H+A4XkCTaTt4oQWf0QW1LlBOm5WBurnQ/obeCzBBbbPPXupEpyYBWJedgb/Ik7WpDVAyYgGo5q/WvXhLTCvgKGEndkcLTrnXaaDXhSLmPisY7/ZwtzZvfdHWGheg3SYGkWG+iL2lHmOdveMgrJlBDATiE+modVGBFzegXuNR8n8xUfCx18x8Qt0WUyUFd7obcMB18//kTmPme3wXw8k+aEtQY2jXUlEIclvZTBGUOqkCkBEe8hyb1mOsoTBqwX/fhhv/a8q0Nl5q2vO3zxAVBO2cLrd6k7lWbFcd/cJ6fEgIErU6cDba++51Q49q8A8BQ1FUgoXaqO+TKafMR3XfDH8yieSWOQVKugUQS1J344LA8gA2himVvB6rJQBjivtUiglt9F3HR6cvbIAhJsnDoDg6dIxXMFgQrPPYF6byle47N4zZCi4C+FQaEKYOM84=
    GEMINI_MODEL_NAME: AgAnuR3yxhXhX12LKC9BSOGK5IzRnFrw0uUgoyJ47uV5Ue7G/k2gaPzX7pAQMIgTmaRq/rPArqhxvgZ+PaPUvYtDfFF7CsdjIPL8IaBzYfn61+uwJb14sJ5Mp5LFMRfEyhPH8evNSjl00gvYktepC05NVA+HahjQcC/A3b+IfVXe7ZFqjfJa4s8p+xIacAUMH+eTbc2QFSPcJZWa0xmwpfnl3d9Q5umBhGjoWUU8BoKGrHdSk8EZTsA2l0rXbT3GdHswwjhKxoBE0PR9gQ8P+tCF9BhR5H6Uz3xE2pySiv1a4/8nY21HmEKT6PrkJnWxReAJwWw+nYwrNNLG0WctO4SWde9bj3Tb41bjoPCOcDk1FAZZVIF8dv7f7gzlMEL7bUdirefJNAuBKOEt2ol7S44qK57IBz6SkMHwE9H8ii9oKOOe4P58O3tmtXt5NuShZz7o4jj3CN6bNV4UJKmD2pfFNn0kF1vwk/ygCyA3o+6uLj5f9dlOdO9ZLz4CdT/KipdVN2uM0MGaBmMtd1RWfdhg+WZk+BzvAdRpgovHkQRTM84g3CwcKiMng7+gOBRswnN73/qFkHEVF/T9JkF2Q3AY38AQpR4Z9bhhFSqSuSA1hpIhHbRCeMB3SzKVTP6DDLsygFs9auiUIOzrj5dmPI3+mM7stVcDsg+saC1VWQab8jLPLB1y8GJrrEq4iQGdr6pHracxdPVrhz8PGxc60FFjQfzkmdisjLDOlvU0sw==
  template:
    metadata:
      name: gemini-api-credentials
      namespace: audiomuse
    type: Opaque
