apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
            - name: recyclarr
              image: ghcr.io/recyclarr/recyclarr:8.7.2@sha256:6e69e009e1cd7493ff6093e8e187b5d3788c75b4a2c0c5127b6a1beda1c19728
              imagePullPolicy: IfNotPresent
              args:
                - sync
              volumeMounts:
                - mountPath: /config
                  name: tmp
                - mountPath: /config/recyclarr.yml
                  name: config
                  subPath: recyclarr.yml
                  readOnly: true
                - mountPath: /config/secrets.yml
                  name: secrets
                  subPath: secret.yml
                  readOnly: true
              securityContext:
                runAsUser: 10001
                runAsGroup: 10001
                capabilities:
                  drop:
                    - ALL
                allowPrivilegeEscalation: false
                privileged: false
                readOnlyRootFilesystem: false
          volumes:
            - name: tmp
              emptyDir:
                medium: Memory
            - name: config
              configMap:
                name: recyclarr-config
            - name: secrets
              secret:
                secretName: recyclarr-secret
          restartPolicy: OnFailure
