apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-app-storage
  namespace: dify
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
