apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress
  - ../../kustomize/components/security-context
  - ../../kustomize/components/tailscale

namePrefix: ollama-
labels:
  - pairs:
      app.kubernetes.io/name: ollama
    includeSelectors: true

images:
  - name: busybox
    newName: ollama/ollama
    newTag: 0.18.2@sha256:5a5d014aa774f78ebe1340c0d4afc2e35afc12a2c3b34c84e71f78ea20af4ba3

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=ollama.internal
      - DIRECT_DOMAIN=ollama.anshulg.direct
      - TS_HOST=ollama

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: Service
    path: patch-service.yaml
