apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncthing
  labels:
    app: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  serviceName: syncthing
  template:
    metadata:
      name: syncthing
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: lscr.io/linuxserver/syncthing:2.1.1@sha256:b1a5a0ea4b32ecf2672db7c4c56443c5e222cca12d397724ea93c07a6c7564d0
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "2018"
            - name: PGID
              value: "3002"
            - name: TZ
              value: "America/Los_Angeles"
          ports:
            - containerPort: 8384
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          hostPath:
            path: /data
      securityContext:
        fsGroup: 3002
      nodeSelector:
        kubernetes.io/hostname: odroid-h4
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
