apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../kustomize/base
  - ../../../kustomize/workloads/deployment
  - env.yaml

components:
  - ../../../kustomize/components/security-context

namePrefix: rreading-glasses-
labels:
  - pairs:
      app.kubernetes.io/name: rreading-glasses
    includeSelectors: true

images:
  - name: busybox
    newName: blampe/rreading-glasses
    newTag: hardcover@sha256:6db4551f77c038516b55dab689f3b473c2c5fdf8f13580b91a8ba39360c3d107

patches:
  - target:
      kind: Deployment
    path: patch-deployment.yaml
  - target:
      kind: Deployment
    path: patch-deployment2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
