apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../kustomize/base
  - ../../../kustomize/workloads/deployment
  - env.yaml

components:
  - ../../../kustomize/components/security-context

namePrefix: rreading-glasses-
labels:
  - pairs:
      app.kubernetes.io/name: rreading-glasses
    includeSelectors: true

images:
  - name: busybox
    newName: blampe/rreading-glasses
    newTag: hardcover@sha256:3f017a51d9007b715303a20f481c822e4df66485fc9e5f57f6fdf1de840dc02f

patches:
  - target:
      kind: Deployment
    path: patch-deployment.yaml
  - target:
      kind: Deployment
    path: patch-deployment2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
