apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset
  - oauth.yaml
  - oauth-config.yaml

components:
  - ../../kustomize/components/ingress

namePrefix: trailarr-
labels:
  - pairs:
      app.kubernetes.io/name: trailarr
    includeSelectors: true

images:
  - name: busybox
    newName: nandyalu/trailarr
    newTag: 0.9.9@sha256:330957e169bd3a00e7abd9867ed1be44e5a595f69eb677eac7f9e5399d68e5a1

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=trailarr.internal

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
      name: svc
    path: patch-service.yaml
  - target:
      kind: IngressRoute
      name: ingress
    path: patch-ingress.yaml
