apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset
  - oauth.yaml
  - oauth-config.yaml

components:
  - ../../kustomize/components/ingress

namePrefix: trailarr-
labels:
  - pairs:
      app.kubernetes.io/name: trailarr
    includeSelectors: true

images:
  - name: busybox
    newName: nandyalu/trailarr
    newTag: 0.9.7@sha256:eee895d56e62d3d8bf7779a44684e30f6216e6e99a01213bda976f4ad553df12

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=trailarr.internal

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
      name: svc
    path: patch-service.yaml
  - target:
      kind: IngressRoute
      name: ingress
    path: patch-ingress.yaml
