apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset
  - oauth.yaml
  - oauth-config.yaml

components:
  - ../../kustomize/components/ingress

namePrefix: trailarr-
labels:
  - pairs:
      app.kubernetes.io/name: trailarr
    includeSelectors: true

images:
  - name: busybox
    newName: nandyalu/trailarr
    newTag: 0.11.5@sha256:bbf4e94d078cacf7d244ebdc30e288875c38dfb1c301fc384be506870365c013

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=trailarr.internal

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
      name: svc
    path: patch-service.yaml
  - target:
      kind: IngressRoute
      name: ingress
    path: patch-ingress.yaml
