apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-proxy
  namespace: trailarr
  labels:
    app.kubernetes.io/component: oauth-proxy
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: oauth-proxy
  template:
    metadata:
      name: oauth-proxy
      annotations:
        linkerd.io/inject: enabled
      labels:
        app.kubernetes.io/component: oauth-proxy
    spec:
      imagePullSecrets:
        - name: docker-regcred
      containers:
        - name: oauth-proxy
          image: dhi.io/oauth2-proxy:7.15.3-debian13@sha256:f6c8360c639f595939f9282855e4b33442af2a48b097369b6180cb3e406d5a58
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4180
              protocol: TCP
          envFrom:
            - secretRef:
                name: trailarr-oauth-config
          livenessProbe:
            httpGet:
              port: 4180
              path: /ping
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 4180
              path: /ready
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
            limits:
              memory: 16Mi
          securityContext:
            runAsUser: 10001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: trailarr
  labels:
    app.kubernetes.io/component: oauth-proxy
spec:
  selector:
    app.kubernetes.io/component: oauth-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4180
  type: ClusterIP
