apiVersion: v1
kind: Service
metadata:
  name: empty
spec:
  selector:
    app.kubernetes.io/name: trailarr
    app.kubernetes.io/component: trailarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7889
