apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/tailscale

namePrefix: prowlarr-
labels:
  - pairs:
      app.kubernetes.io/name: prowlarr
    includeSelectors: true

images:
  - name: busybox
    newName: linuxserver/prowlarr
    newTag: 2.4.0-nightly@sha256:9ec633c2dc47bede5db25dfe064da270c2c2c6f08a745b8d85b185077161f2c7

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=prowlarr.internal
      - TS_HOST=prowlarr
  - name: env-config
    literals:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
