apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibre
  labels:
    app: calibre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      name: calibre
      annotations:
        linkerd.io/inject: "enabled"
      labels:
        app: calibre
    spec:
      containers:
        - name: calibre
          image: linuxserver/calibre:9.2.1@sha256:e28679665f23d0f4c65f87b94aedba324e8355051643ca85b1dea402e02a1602
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "2005"
            - name: PGID
              value: "3002"
            - name: TZ
              value: "America/Los_Angeles"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
            - containerPort: 8081
              protocol: TCP
              name: content
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /config
              name: config
      securityContext:
        fsGroup: 3002
      restartPolicy: Always
      volumes:
        - name: data
          hostPath:
            path: /data
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
