apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-dhi-images
  annotations:
    policies.kyverno.io/title: Verify Docker Hardened Images
    policies.kyverno.io/category: Software Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.14.0
    policies.kyverno.io/description: >-
      Verifies all dhi.io container images are signed with Docker's official
      DHI Cosign key. Unsigned or tampered images are denied at admission.
spec:
  validationFailureAction: Enforce
  background: false
  webhookConfiguration:
    timeoutSeconds: 30
  rules:
    - name: verify-dhi-images
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
                - UPDATE
      verifyImages:
        - imageReferences:
            - "dhi.io/*"
          cosignOCI11: true
          mutateDigest: false
          verifyDigest: true
          required: true
          imageRegistryCredentials:
            allowInsecureRegistry: false
            secrets:
              - docker-regcred
          attestors:
            - entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKdROmntRJFBrOJOQF5ww6gDBJqGm
                      Fxa4333s1KsL9ISjtmRzGNih9lNRsqfRVjgFgJIdL6EQ9dohdanvn7r2cg==
                      -----END PUBLIC KEY-----
                    rekor:
                      url: "https://rekor.sigstore.dev/"
                      ignoreTlog: true
                    ctlog:
                      ignoreSCT: true
