apiVersion: policies.kyverno.io/v1
kind: GeneratingPolicy
metadata:
  name: image-pull-secret
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE', 'UPDATE']
        resources: ['namespaces']
  variables:
    - name: targetNs
      expression: 'object.metadata.name'
    - name: sourceSecret
      expression: resource.Get("v1", "secrets", "default", "docker-regcred")
  generate:
    - expression: generator.Apply(variables.targetNs, [variables.sourceSecret])
