apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset
  - secrets.yaml
  - middleware.yaml

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress

namePrefix: transmute-
labels:
  - pairs:
      app.kubernetes.io/name: transmute
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/transmute-app/transmute
    newTag: 0.12.0@sha256:ebf1e10ab407a6f98497919fcc13dad8eecb20f1299714eb2ec1c0f72c9556e2

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=transmute.internal
      - DIRECT_DOMAIN=transmute.anshulg.direct

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
  - target:
      group: traefik.io
      kind: IngressRoute
      version: v1alpha1
    path: patch-ingress.yaml
