apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/base
  - ../../kustomize/workloads/statefulset
  - secrets.yaml
  - middleware.yaml

components:
  - ../../kustomize/components/ingress
  - ../../kustomize/components/direct-ingress

namePrefix: transmute-
labels:
  - pairs:
      app.kubernetes.io/name: transmute
    includeSelectors: true

images:
  - name: busybox
    newName: ghcr.io/transmute-app/transmute
    newTag: 1.3.1@sha256:61dbb43f6f29cd46d659534c0ec19faa4d0c50ea3a62630d313e8b7fef528bdb

configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=transmute.internal
      - DIRECT_DOMAIN=transmute.anshulg.direct

patches:
  - target:
      kind: StatefulSet
    path: patch-statefulset.yaml
  - target:
      kind: StatefulSet
    path: patch-statefulset2.yaml
  - target:
      kind: Service
    path: patch-service.yaml
  - target:
      group: traefik.io
      kind: IngressRoute
      version: v1alpha1
    path: patch-ingress.yaml
