apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smokeping
  labels:
    app: smokeping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smokeping
  serviceName: smokeping
  template:
    metadata:
      name: smokeping
      labels:
        app: smokeping
    spec:
      containers:
        - name: smokeping
          image: lscr.io/linuxserver/smokeping:2.9.0@sha256:ebfbbc32a51612de154b6c0c105836ae40905411cbac43592257afce727c0534
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "10001"
            - name: PGID
              value: "10001"
            - name: TZ
              value: "America/Los_Angeles"
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /smokeping/
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /smokeping/
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      initContainers:
        - name: copy-config
          image: busybox:1.38.0@sha256:b6762ddf4a50aabb5f4d21aa6f447d05d5633fb09f09c08b33f22356a2f98be0
          command:
            - cp
            - /configmap/Targets
            - /config/Targets
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /configmap
              name: configmap
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      volumes:
        - name: configmap
          configMap:
            name: smokeping-config
      restartPolicy: Always
      securityContext:
        fsGroup: 10001
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app: smokeping
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Mi
    - metadata:
        name: data
        labels:
          app: smokeping
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
