apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smokeping
  labels:
    app: smokeping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smokeping
  serviceName: smokeping
  template:
    metadata:
      name: smokeping
      labels:
        app: smokeping
    spec:
      containers:
        - name: smokeping
          image: lscr.io/linuxserver/smokeping:2.9.0@sha256:311d44c5a162f724b8d48f7a26bd604152d409f6249197ff2c7190f496db87d9
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "10001"
            - name: PGID
              value: "10001"
            - name: TZ
              value: "America/Los_Angeles"
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /smokeping/
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /smokeping/
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      initContainers:
        - name: copy-config
          image: busybox:1.37.0@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
          command:
            - cp
            - /configmap/Targets
            - /config/Targets
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /configmap
              name: configmap
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      volumes:
        - name: configmap
          configMap:
            name: smokeping-config
      restartPolicy: Always
      securityContext:
        fsGroup: 10001
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app: smokeping
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Mi
    - metadata:
        name: data
        labels:
          app: smokeping
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
