apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: empty
spec:
  template:
    spec:
      securityContext:
        supplementalGroups:
          - 3002 # dataapps - for /data/BookImport access
      containers:
        - name: app
          env:
            - name: HIJACK_OUT
              value: "1"
            - name: RECEIVER_SERVER_URL
              value: "http://beets-import.beets.svc.cluster.local"
            - name: BOOK_DEST
              value: /bookimport
          envFrom:
            - secretRef:
                name: qui-secrets
          volumeMounts:
            - mountPath: /config
              name: data
            - mountPath: /sender
              name: beets-sender
              # Doesn't work right now
              # See https://github.com/kubernetes/kubernetes/issues/134894
              # subPath: usr/local/bin/sender
              readOnly: true
            - mountPath: /book-copier
              name: book-copier
              readOnly: true
            - mountPath: /bookimport
              name: bookimport
          readinessProbe:
            httpGet:
              port: 7476
              path: /health
      volumes:
        - name: beets-sender
          image:
            reference: ghcr.io/ansg191/torrent-beets-importer/sender:v0.1.2@sha256:92ec10be6de66efc927c98d31b19eee6aee2c6e03a06e8cc1590c023d19b2608
            pullPolicy: IfNotPresent
        - name: book-copier
          image:
            reference: ghcr.io/ansg191/qui-book-copier:main@sha256:152a633bbc7df6e3b0b763681eca5a5ff10731f1e002cdfc722fc2409100ebc9
            pullPolicy: Always
        - name: bookimport
          hostPath:
            path: /data/BookImport
